// usage: log('inside coolFunc', this, arguments);
// paulirish.com/2009/log-a-lightweight-wrapper-for-consolelog/
window.log = function f(){ log.history = log.history || []; log.history.push(arguments); if(this.console) { var args = arguments, newarr; args.callee = args.callee.caller; newarr = [].slice.call(args); if (typeof console.log === 'object') log.apply.call(console.log, console, newarr); else console.log.apply(console, newarr);}};

// make it safe to use console.log always
(function(a){function b(){}for(var c="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),d;!!(d=c.pop());){a[d]=a[d]||b;}})
(function(){try{console.log();return window.console;}catch(a){return (window.console={});}}());


// tweetable 1.7.1 - jQuery twitter feed generator plugin
(function(e){jQuery.fn.tweetable=function(t){t=e.extend({},e.fn.tweetable.options,t);return this.each(function(){var e=jQuery(this),n=jQuery('<ul class="tweetList">')[t.position.toLowerCase()+"To"](e),r=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],i="http://api.getmytweets.co.uk/?screenname=",s="&limit=",o,u,a,f,l;jQuery.getJSON(i+t.username+s+t.limit,e,function(e){o=e&&e.error||null;if(o){n.append('<li class="tweet_content item"><p class="tweet_link">'+t.failed+"</p></li>");return}jQuery.each(e.tweets,function(e,i){if(e>=t.limit)return;n.append('<li class="tweet_content_'+e+'"><p class="tweet_link_'+e+'">'+i.response.replace(/#(.*?)(\s|$)/g,'<span class="hash">#$1 </span>').replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,'<a href="$&">$&</a> ').replace(/@(.*?)(\s|\(|\)|$)/g,'<a href="http://twitter.com/$1">@$1 </a>$2')+"</p></li>");if(t.time===true){for(f=0;f<=12;f++){if(r[f]===i.tweet_date.substr(4,3)){a=f+1;u=a<10?"0"+a:a}}var s=i.tweet_date.substr(26,4)+"-"+u+"-"+i.tweet_date.substr(8,2)+"T"+i.tweet_date.substr(11,8)+"Z";jQuery(".tweet_link_"+e).append('<p class="timestamp"><'+(t.html5?'time datetime="'+s+'"':"small")+"> "+i.tweet_date.substr(8,2)+"/"+u+"/"+i.tweet_date.substr(26,4)+", "+i.tweet_date.substr(11,5)+"</"+(t.html5?"time":"small")+"></p>")}});if(t.rotate===true){var i=n.find("li"),s=i.length||null,l=0,c=t.speed;if(!s)return;function h(){i.eq(l++).fadeOut(400,function(){l=l===s?0:l;i.eq(l).fadeIn(400)})}i.slice(1).hide();setInterval(h,c)}t.onComplete(n)})})};e.fn.tweetable.options={limit:5,username:"philipbeel",time:false,rotate:false,speed:5e3,replies:false,position:"append",failed:"No tweets available",html5:false,retweets:false,onComplete:function(e){}}})(jQuery)
