name: Pierrick CAEN
url: https://pierrickcaen.fr
timezone: Europe/Paris
permalink: /blog/:title.html
markdown: kramdown
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html
sass:
  style: :compressed
coffee:
  style: :compressed
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "bicycleparking/*"
    values:
      sitemap:         false
